### ISSUE TITLE
PRACTICA TEST CASE

### ISSUE THREAD

**Issue by Nancy2050** [SistemasTecTlaxiaco/practica-de-test-case-entrevista#2]
[REPORTE DE PRACTICA 6_TEST CASE.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-test-case-entrevista/files/7343705/REPORTE.DE.PRACTICA.6_TEST.CASE.pdf)

**Comment by MaGuadalupeQuiroz** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Solo parece que no hicieron solicitudes de extracción

**Comment by josealfredo79** [comment]
Bien hecho y revisado
